### ISSUE TITLE
iGEM Distribution 2022 Finalization

### ISSUE THREAD

**Issue by jcahill** [friendzymes/community#25]
# TODOs

## Parts

- [x] Add ApaLI restriction site flankers.
- [ ] All of Isaac L's list of parts.
- [ ] All preexisting bsub designs
- [x] [review isaac G's draft](https://benchling.com/s/seq-jMwf7EKrH4fuXvHc7FqD?m=slm-vezjnWGtCBHLA3h1sWyo)

## Description

 - [ ] Create a README.md file
   - [ ] Describe components of AllClo
   - [ ] Describe parts collection
   - [ ] Attribution and so forth

## Package / Submission

- [ ] Finalize parts lists and template in Benchling and GSheets
- [ ] Add and double-check metadata, ex. authors
- [ ] Export to our github fork.
- [ ] Submit merge request of our github fork to iGEM-distribution repo.

# 2022-02-10 Submission Roundup

## Links

- Package WIP
  - top-level directory: [github][1], [google drive][2]
  - views subdirectory: [github][3], [google drive][4]
- Benchling Drafts
  - [AllCloPartsAndOverhangsSummary][5]
  - Finalized Parts: [benchling/@friendzymes/iGEM Distribution Kit 2022 - Friendzymes Collection][6]

## Preliminary list of parts to design and submit for synthesis in the iGEM Distro

- [ ] FiveClo/ThreeClo recombination sites
- [ ] Ribozyme insulator parts - [google spreadsheet][7]
- [ ] Part type switching linkers and an expanded level 2 assembly linker set (using BbsI and mBsaI)
- [ ] Universal dropout cassette + DOclo linkers
- [ ] HpaII and MspI CDS/TU parts
- [ ] Split E. coli selection markers - benchling template files: [8], [9]
- [ ] More homology arms for Bsub, Pichia and E. coli
- [ ] More constitutive and inducible promoters for Bsub and Pichia 
- [ ] More Bsub RBSs
- [ ] CDSs for auxotrophic selection markers in Bsub and Pichia (+Pichia ku70)
- [ ] CDSs for recombinases to go with the FiveClo/ThreeClo recombination sites
- [ ] All our existing Bsub wetware part designs, adapted as needed for AllClo
- [ ] CDSs for Bsub and Pichia counterselection markers

### Stuff from this list that's new

- FiveClo/ThreeClo recombination sites
- More ribozyme insulator parts
- Part type switching linkers and an expanded level 2 assembly linker set
- Universal dropout cassette and DOclo linkers
- HpaII and MspI CDS/TU parts
- More split E. coli selection markers?
- More homology arms for Bsub, Pichia and E. coli
- More constitutive and inducible promoters for Bsub and Pichia
- More Bsub RBSs
- CDSs for auxotrophic selection markers in Bsub and Pichia (+Pichia ku70)
- CDSs for recombinases to go with the FiveClo/ThreeClo recombination sites
- CDSs for Bsub and Pichia counterselection markers
- Homology arms to knock out Pichia proteases PEP4 and PRB1

# 2022-02-06 Weekly Meet

Action Items

- iGEM Distribution collection discussion.
- Parts / Design Elements
  - Add ApaLI restriction site flankers.
  - All of Isaac L's list of parts.
  - review isaac G's draft, particularly overhangs
    - https://benchling.com/s/seq-jMwf7EKrH4fuXvHc7FqD?m=slm-vezjnWGtCBHLA3h1sWyo
- Description
  - Create a README.md file referencing the authors of each part
  - Ask in github issues about including our own non-automated README for collection.
- Submission workflow:
  1. Finalize parts lists and template in Benchling and GSheets
  2. Export to our github fork.
  3. Submit merge request of our github fork to iGEM-distribution repo.

---

[1]: https://github.com/friendzymes/iGEM-distribution/tree/develop/Friendzymes%20Collection/
[2]: https://drive.google.com/drive/folders/1niahyNw_Cse-2EaW0j7bF0WihoNenUWt
[3]: https://github.com/friendzymes/iGEM-distribution/tree/develop/Friendzymes%20Collection/views
[4]: https://drive.google.com/drive/folders/1a-vJQ6zF_Vc2WpvjTuhg-Uk5g_AhDZIa
[5]: https://benchling.com/s/seq-tOr654P4EAAOVFP8mrtD?m=slm-tsyKSGlbgsd57T5ElPP3
[6]: https://benchling.com/friendzymes/f_/Wqom0gRT-igem-distribution-kit-2022-friendzymes-collection/
[7]: https://docs.google.com/spreadsheets/d/1q2wYGu1rDuWyRxzMg9lLueSZII8O9yy2qsgnYuaxbcM/edit
[8]: https://benchling.com/s/seq-2ylxt6V9CFbhLNHv9QWi?m=slm-F4gOYBmK0Raiu6h1P1il
[9]: https://benchling.com/s/seq-fEnuc1Ad2n1fPABHZziD?m=slm-9orUbD5tukrMMB506QmM

**Comment by jcahill** [comment]
https://github.com/iGEM-Engineering/iGEM-distribution/pull/238

**Comment by jcahill** [comment]
Internal target for wrapping up final release candidate (soft): 2022-02-21
